function escPs(s) {
    return (s || '').replace(/'/g, "''");
}

function writeDualAdminPsScript(psScriptPath, ip, a1User, a1CurPass, a1NewPass, a2User, a2NewPass, method, isVerifyOnly) {
    var hasAdmin2 = !!(a2User && a2NewPass);
    var lines = [];

    if (method === 'wmi') {
        lines = [
            "$ErrorActionPreference = 'SilentlyContinue'",
            "$ip = '" + escPs(ip) + "'",
            "$a1 = '" + escPs(a1User) + "'; $a1Old = '" + escPs(a1CurPass) + "'; $a1New = '" + escPs(a1NewPass) + "'",
            "$a2 = '" + escPs(a2User) + "'; $a2New = '" + escPs(a2NewPass) + "'",
            "$hasA2 = " + (hasAdmin2 ? '$true' : '$false'),
            "$isVerify = " + (isVerifyOnly ? '$true' : '$false'),
            "",
            "function Test-WmiCred($u, $p) {",
            "  $sec = ConvertTo-SecureString $p -AsPlainText -Force",
            "  $auth = if ($u -match '\\\\') { $u } else { \"$ip\\$u\" }",
            "  $cr = New-Object Management.Automation.PSCredential($auth, $sec)",
            "  $null = Get-WmiObject Win32_OperatingSystem -ComputerName $ip -Credential $cr -ErrorAction Stop",
            "  return $cr",
            "}",
            "",
            "if ($isVerify) {",
            "  $v1 = $false; $v2 = $true",
            "  try { $v1 = (Test-WmiCred $a1 $a1New) -ne $null } catch {}",
            "  if ($hasA2) { $v2 = $false; try { $v2 = (Test-WmiCred $a2 $a2New) -ne $null } catch {} }",
            "  if ($v1 -and $v2) { Write-Output 'RES:SUCCESS:Xac thuc Mat khau MOI thanh cong qua WMI [Port 135] [Verified OK]' }",
            "  else { Write-Output 'RES:FAIL:Xac thuc that bai qua WMI: Sai mat khau moi hoac Port 135 dong' }",
            "  exit",
            "}",
            "",
            "$cred = $null",
            "try { $cred = Test-WmiCred $a1 $a1Old } catch {}",
            "if (-not $cred) { try { $cred = Test-WmiCred $a1 $a1New } catch {} }",
            "if (-not $cred) {",
            "  $err = if ($Error[0]) { $Error[0].Exception.Message } else { 'Sai mat khau hoac Port 135 dong' }",
            "  Write-Output ('RES:FAIL:Phuong thuc WMI RPC (Port 135) khong hoat dong: ' + $err); exit",
            "}",
            "",
            "$netCmd = if ($hasA2) { \"cmd.exe /c net user `\"$a2`\" `\"$a2New`\" & net user `\"$a1`\" `\"$a1New`\"\" } else { \"cmd.exe /c net user `\"$a1`\" `\"$a1New`\"\" }",
            "$res = Invoke-WmiMethod -Class Win32_Process -Name Create -ArgumentList $netCmd -ComputerName $ip -Credential $cred",
            "if ($res.ReturnValue -ne 0) {",
            "  Write-Output ('RES:FAIL:Phuong thuc WMI khong hoat dong: Loi tao tien trinh (Code ' + $res.ReturnValue + ')'); exit",
            "}",
            "",
            "Start-Sleep -Seconds 1",
            "$v1 = $false; $v2 = $true",
            "try { $v1 = (Test-WmiCred $a1 $a1New) -ne $null } catch {}",
            "if ($hasA2) {",
            "  $v2 = $false",
            "  try { $v2 = (Test-WmiCred $a2 $a2New) -ne $null } catch {}",
            "}",
            "if ($v1 -and $v2) {",
            "  $msg = if ($hasA2) { 'Hoan tat ca 2 qua WMI RPC [Port 135] [Verified OK]' } else { 'Hoan tat Admin 1 qua WMI RPC [Port 135] [Verified OK]' }",
            "  Write-Output ('RES:SUCCESS:' + $msg)",
            "} else {",
            "  Write-Output ('RES:FAIL:Phuong thuc WMI khong hoat dong: Verify mat khau moi that bai')",
            "}"
        ];
    } else if (method === 'schtasks') {
        lines = [
            "$ErrorActionPreference = 'SilentlyContinue'",
            "$ip = '" + escPs(ip) + "'",
            "$a1 = '" + escPs(a1User) + "'; $a1Old = '" + escPs(a1CurPass) + "'; $a1New = '" + escPs(a1NewPass) + "'",
            "$a2 = '" + escPs(a2User) + "'; $a2New = '" + escPs(a2NewPass) + "'",
            "$hasA2 = " + (hasAdmin2 ? '$true' : '$false'),
            "$isVerify = " + (isVerifyOnly ? '$true' : '$false'),
            "",
            "function Test-AdsiCred($u, $p) {",
            "  $auth = if ($u -match '\\\\') { $u } else { \"$ip\\$u\" }",
            "  $de = New-Object System.DirectoryServices.DirectoryEntry(\"WinNT://$ip/$u,user\", $auth, $p)",
            "  $null = $de.NativeObject",
            "  return $de",
            "}",
            "",
            "if ($isVerify) {",
            "  $v1 = $false; $v2 = $true",
            "  try { $v1 = (Test-AdsiCred $a1 $a1New) -ne $null } catch {}",
            "  if ($hasA2) { $v2 = $false; try { $v2 = (Test-AdsiCred $a2 $a2New) -ne $null } catch {} }",
            "  if ($v1 -and $v2) { Write-Output 'RES:SUCCESS:Xac thuc Mat khau MOI thanh cong qua Schtasks/RPC [Port 135/445] [Verified OK]' }",
            "  else { Write-Output 'RES:FAIL:Xac thuc that bai qua Schtasks/RPC: Sai mat khau moi hoac Port 135/445 dong' }",
            "  exit",
            "}",
            "",
            "$validAuthPass = $null",
            "try { $null = Test-AdsiCred $a1 $a1Old; $validAuthPass = $a1Old } catch {}",
            "if (-not $validAuthPass) {",
            "  try { $null = Test-AdsiCred $a1 $a1New; $validAuthPass = $a1New } catch {}",
            "}",
            "if (-not $validAuthPass) {",
            "  $err = if ($Error[0]) { $Error[0].Exception.Message } else { 'Sai mat khau hoac Port 135/445 dong' }",
            "  Write-Output ('RES:FAIL:Phuong thuc Schtasks khong hoat dong: ' + $err); exit",
            "}",
            "",
            "$tName = 'PwdTask_' + (Get-Random -Minimum 10000 -Maximum 99999)",
            "$cmdLine = if ($hasA2) { \"cmd.exe /c net user `\"$a2`\" `\"$a2New`\" & net user `\"$a1`\" `\"$a1New`\"\" } else { \"cmd.exe /c net user `\"$a1`\" `\"$a1New`\"\" }",
            "",
            "$cArgs = \"/create /s `\"$ip`\" /u `\"$a1`\" /p `\"$validAuthPass`\" /ru SYSTEM /tn `\"$tName`\" /tr `\"$cmdLine`\" /sc ONCE /st 00:00 /f\"",
            "$pCreate = Start-Process schtasks.exe -ArgumentList $cArgs -Wait -NoNewWindow -PassThru",
            "if ($pCreate.ExitCode -ne 0) {",
            "  Write-Output ('RES:FAIL:Schtasks loi tao task (ExitCode ' + $pCreate.ExitCode + ')'); exit",
            "}",
            "",
            "$rArgs = \"/run /s `\"$ip`\" /u `\"$a1`\" /p `\"$validAuthPass`\" /tn `\"$tName`\"\"",
            "$null = Start-Process schtasks.exe -ArgumentList $rArgs -Wait -NoNewWindow",
            "",
            "Start-Sleep -Seconds 2",
            "",
            "$dArgs = \"/delete /s `\"$ip`\" /u `\"$a1`\" /p `\"$validAuthPass`\" /tn `\"$tName`\" /f\"",
            "$null = Start-Process schtasks.exe -ArgumentList $dArgs -Wait -NoNewWindow",
            "",
            "Start-Sleep -Seconds 1",
            "$v1 = $false; $v2 = $true",
            "try { $v1 = (Test-AdsiCred $a1 $a1New) -ne $null } catch {}",
            "if ($hasA2) {",
            "  $v2 = $false",
            "  try { $v2 = (Test-AdsiCred $a2 $a2New) -ne $null } catch {}",
            "}",
            "if ($v1 -and $v2) {",
            "  $msg = if ($hasA2) { 'Hoan tat ca 2 qua Schtasks [Port 135/445] [Verified OK]' } else { 'Hoan tat Admin 1 qua Schtasks [Port 135/445] [Verified OK]' }",
            "  Write-Output ('RES:SUCCESS:' + $msg)",
            "} else {",
            "  Write-Output ('RES:FAIL:Phuong thuc Schtasks: Task da chay nhung Verify mat khau moi that bai')",
            "}"
        ];
    } else {
        lines = [
            "$ErrorActionPreference = 'SilentlyContinue'",
            "$ip = '" + escPs(ip) + "'",
            "$a1 = '" + escPs(a1User) + "'; $a1Old = '" + escPs(a1CurPass) + "'; $a1New = '" + escPs(a1NewPass) + "'",
            "$a2 = '" + escPs(a2User) + "'; $a2New = '" + escPs(a2NewPass) + "'",
            "$hasA2 = " + (hasAdmin2 ? '$true' : '$false'),
            "$isVerify = " + (isVerifyOnly ? '$true' : '$false'),
            "",
            "function Test-AdsiCred($u, $p) {",
            "  $auth = if ($u -match '\\\\') { $u } else { \"$ip\\$u\" }",
            "  $de = New-Object System.DirectoryServices.DirectoryEntry(\"WinNT://$ip/$u,user\", $auth, $p)",
            "  $null = $de.NativeObject",
            "  return $de",
            "}",
            "",
            "if ($isVerify) {",
            "  $v1 = $false; $v2 = $true",
            "  try { $v1 = (Test-AdsiCred $a1 $a1New) -ne $null } catch {}",
            "  if ($hasA2) { $v2 = $false; try { $v2 = (Test-AdsiCred $a2 $a2New) -ne $null } catch {} }",
            "  if ($v1 -and $v2) { Write-Output 'RES:SUCCESS:Xac thuc Mat khau MOI thanh cong qua ADSI/SMB [Port 445] [Verified OK]' }",
            "  else { Write-Output 'RES:FAIL:Xac thuc that bai qua ADSI/SMB: Sai mat khau moi hoac Port 445 dong' }",
            "  exit",
            "}",
            "",
            "function Set-AdsiPwd($targetUser, $authU, $authP, $newP) {",
            "  $auth = if ($authU -match '\\\\') { $authU } else { \"$ip\\$authU\" }",
            "  $de = New-Object System.DirectoryServices.DirectoryEntry(\"WinNT://$ip/$targetUser,user\", $auth, $authP)",
            "  $de.Invoke('SetPassword', @($newP))",
            "  $de.CommitChanges()",
            "}",
            "",
            "$validAuthPass = $null",
            "try { $null = Test-AdsiCred $a1 $a1Old; $validAuthPass = $a1Old } catch {}",
            "if (-not $validAuthPass) {",
            "  try { $null = Test-AdsiCred $a1 $a1New; $validAuthPass = $a1New } catch {}",
            "}",
            "if (-not $validAuthPass) {",
            "  $err = if ($Error[0]) { $Error[0].Exception.Message } else { 'Sai mat khau hoac Port 445 dong' }",
            "  Write-Output ('RES:FAIL:Phuong thuc ADSI/SMB (Port 445) khong hoat dong: ' + $err); exit",
            "}",
            "",
            "try {",
            "  if ($hasA2) { Set-AdsiPwd $a2 $a1 $validAuthPass $a2New }",
            "  Set-AdsiPwd $a1 $a1 $validAuthPass $a1New",
            "} catch {",
            "  $err = if ($Error[0]) { $Error[0].Exception.Message } else { 'Loi doi mat khau' }",
            "  Write-Output ('RES:FAIL:Phuong thuc ADSI/SMB (Port 445) khong hoat dong: ' + $err); exit",
            "}",
            "",
            "Start-Sleep -Seconds 1",
            "$v1 = $false; $v2 = $true",
            "try { $v1 = (Test-AdsiCred $a1 $a1New) -ne $null } catch {}",
            "if ($hasA2) {",
            "  $v2 = $false",
            "  try { $v2 = (Test-AdsiCred $a2 $a2New) -ne $null } catch {}",
            "}",
            "if ($v1 -and $v2) {",
            "  $msg = if ($hasA2) { 'Hoan tat ca 2 qua ADSI/SMB [Port 445] [Verified OK]' } else { 'Hoan tat Admin 1 qua ADSI/SMB [Port 445] [Verified OK]' }",
            "  Write-Output ('RES:SUCCESS:' + $msg)",
            "} else {",
            "  Write-Output ('RES:FAIL:Phuong thuc ADSI/SMB (Port 445) khong hoat dong: Verify mat khau moi that bai')",
            "}"
        ];
    }

    var wf = fso.CreateTextFile(psScriptPath, true);
    wf.Write(lines.join('\r\n'));
    wf.Close();
}
